// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/microhq/greeting-api/proto/hello/hello.proto

/*
Package go_micro_api_greeting is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/greeting-api/proto/hello/hello.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_api_greeting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Greeting service

type GreetingService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type greetingService struct {
	c    client.Client
	name string
}

func NewGreetingService(name string, c client.Client) GreetingService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.greeting"
	}
	return &greetingService{
		c:    c,
		name: name,
	}
}

func (c *greetingService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Greeting.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeting service

type GreetingHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterGreetingHandler(s server.Server, hdlr GreetingHandler, opts ...server.HandlerOption) error {
	type greeting interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Greeting struct {
		greeting
	}
	h := &greetingHandler{hdlr}
	return s.Handle(s.NewHandler(&Greeting{h}, opts...))
}

type greetingHandler struct {
	GreetingHandler
}

func (h *greetingHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.GreetingHandler.Hello(ctx, in, out)
}
